config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/privacy', to: 'static_pages#privacy'
  get '/terms', to: 'static_pages#terms'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def privacy
  end

  def terms
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_notification.html.erb
<% flash.each do |key, value| %>
  <% if key == 'alert' or key == 'notice' %>
    <%= content_tag(:div, value, class: "flash #{key}", id: "#{key}") %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RRRails Template</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <noscript>
      <meta http-equiv="refresh" content="2;url=nojavascript.html">
    </noscript>
    
  </head>

  <body class="min-h-screen">
    <nav class="flex items-center justify-between flex-wrap bg-green-700 p-6">
      <div class="flex items-center flex-no-shrink text-white mr-6">
        <svg class="h-8 w-8 mr-2" width="54" height="54" viewBox="0 0 54 54" xmlns="http://www.w3.org/2000/svg"><path d="M13.5 22.1c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05zM0 38.3c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05z"/></svg>
        <span class="font-semibold text-xl tracking-tight">RRRails Template</span>
      </div>
      <div class="block lg:hidden">
        <button class="flex items-center px-3 py-2 border rounded text-teal-lighter border-teal-light hover:text-white hover:border-white">
          <svg class="h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
        </button>
      </div>
      <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
        <div class="text-sm lg:flex-grow">
          <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 text-teal-lighter hover:text-white mr-4">
            <%= link_to "About", about_path %>
          </a>
          <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 text-teal-lighter hover:text-white mr-4">
            <%= link_to "Privacy", privacy_path %>
          </a>
          <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 text-teal-lighter hover:text-white">
            <%= link_to "Terms of Use", terms_path %>
          </a>
        </div>
      </div>
      <% if user_signed_in? %>
        <div class="text-right">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'text-right' %>
        </div>
      <% else %>
        <div class="text-right">
          <%= link_to 'Sign In', new_user_session_path %>
        </div>
      <% end %>
    </nav>
    <div  class="container mx-auto px-4">


      <%= yield %>
    </div>
    <footer class="footer bg-white relative pt-1 border-b-2 border-green-700">
        <div class="container mx-auto px-6">

            <div class="sm:flex sm:mt-8">
                <div class="mt-8 sm:mt-0 sm:w-full sm:px-8 flex flex-col md:flex-row justify-between">
                    <div class="flex flex-col">
                        <span class="font-bold text-gray-700 uppercase mb-2">Footer header 1</span>
                        <span class="my-2"><a href="#" class="text-blue-700  text-md hover:text-blue-500">link 1</a></span>
                        <span class="my-2"><a href="#" class="text-blue-700  text-md hover:text-blue-500">link 1</a></span>
                        <span class="my-2"><a href="#" class="text-blue-700  text-md hover:text-blue-500">link 1</a></span>
                    </div>
                    <div class="flex flex-col">
                        <span class="font-bold text-gray-700 uppercase mt-4 md:mt-0 mb-2">Footer header 2</span>
                        <span class="my-2"><a href="#" class="text-blue-700 text-md hover:text-blue-500">link 1</a></span>
                        <span class="my-2"><a href="#" class="text-blue-700  text-md hover:text-blue-500">link 1</a></span>
                        <span class="my-2"><a href="#" class="text-blue-700 text-md hover:text-blue-500">link 1</a></span>
                    </div>
                    <div class="flex flex-col">
                        <span class="font-bold text-gray-700 uppercase mt-4 md:mt-0 mb-2">Footer header 3</span>
                        <span class="my-2"><%= link_to 'Admin', admin_root_path, class:"text-blue-700  text-md hover:text-blue-500"%></span>
                        <span class="my-2"><a href="#" class="text-blue-700  text-md hover:text-blue-500">link 1</a></span>
                        <span class="my-2"><a href="#" class="text-blue-700  text-md hover:text-blue-500">link 1</a></span>
                    </div>
                </div>
            </div>
        </div>
        <div class="container mx-auto px-6">
            <div class="mt-16 border-t-2 border-gray-300 flex flex-col items-center">
                <div class="sm:w-2/3 text-center py-2">
                    <p class="text-sm text-blue-700 font-bold mb-2">
                        <%= "#{Time.now.year} \u00A9" %> Regents of the University of Michigan
                    </p>
                </div>
            </div>
        </div>
    </footer>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>About the NELP program</h1>
<p>
  NELP is a University of Michigan academic program that takes place off campus 
  during the Spring half term. UM faculty and other instructors teach the courses, 
  and students earn nine regular UM credits in upper-level English classes. The program 
  takes place at Camp Kabeyun on Lake Winnipesaukee in New Hampshire. For six and a 
  half weeks, 40 students and 13 UM instructors live and work together closely, reading 
  New England authors, writing, and exploring the New England countryside, its people, 
  culture, and history. <%= link_to '...more', 'https://lsa.umich.edu/nelp/prospective-students/about-us.html' %>
</p>
<p>
  This portal is for applicants to submit their payments.
</p>

app/views/static_pages/home.html.erb
<h1 class="text-5xl font-bold text-center my-20">Your Instant Rails App Works!</h1>

app/views/static_pages/privacy.erb
<h1>Website Privacy Notice</h1>
<h4>Overview</h4>
<p>
  The University of Michigan recognizes and values the privacy of the university 
  community members and its guests, and strives to be the leaders and best in the 
  ways in which we manage your personal information. This value is reflected in 
  Regent’s Bylaw Sec. 14.07. Privacy and Access to Information, which states in 
  part:

  “In collecting, utilizing, and releasing information about individuals associated 
  with the university, the university will strive to protect individual privacy, 
  to use information only for the purpose for which it was collected, and to 
  inform individuals of the personal information about them that is being 
  collected, used, or released.”

  In principle, the University of Michigan strives to:

  Collect, store, and use the minimum amount of personal information that is necessary for its legitimate business purposes, and to comply with legal obligations.
  Take reasonable steps to ensure the personal information we manage is accurate and up-to-date.
  Limit who has access to the personal information in our possession to only those who need it for a legitimate, specific purpose.
  Protect personal information through appropriate physical and technical security measures tailored to the sensitivity of the personal data we hold.
  Communicate with our students, faculty, employees, suppliers, partners, and others about how we use personal information in our day-to-day operations.
  Provide opportunities to control your personal information, as permitted by applicable United States and other laws.
  Integrate privacy in the design of our activities when that involves the use of personal data.
  The full content of the <%= link_to 'U-M Website Privacy Notice', 'https://umich.edu/about/privacy/' %>
</p>

app/views/static_pages/terms.html.erb
<h1>U-M Network Responsible Use Agreement</h1>

<p>
  Access to the University of Michigan’s networks is provided in support of students’ academic and research activities, as well as reasonable and appropriate personal use.

  Read the information 
  <%= link_to 'here', 'https://its.umich.edu/enterprise/wifi-networks/network-responsible-use-agreement' %> 
  carefully as it specifies user responsibilities and responsible use standards for connecting 
  to computer networks, including those in residence halls and Northwood Apartments.
  You must agree to the terms and conditions outlined 
  <%= link_to 'here', 'https://its.umich.edu/enterprise/wifi-networks/network-responsible-use-agreement' %>
   to use the networks.
</p>